source_directories:
  - /storage

# Paths to local or remote repositories.
repositories:
  - path: /media/sarg/500GB/backup
    label: local

exclude_if_present:
  - .borgbackupexclude

storage:
  archive_name_format: "{hostname}-{now:%Y-%m-%d_%H-%M}"

keep_hourly: 5
keep_daily: 7
keep_weekly: 4
keep_monthly: 6
keep_yearly: 3

checks:
  - name: repository
  - name: archives
